Add domain expiry check script
qburst/DevOps-Automations pull request #27
Opened 2023-09-05 05:58 UTC by vyshnavlalqburst

Added bash script to check the domain expiry and send alerts. Also updated the README.md file under scripts.

2023-09-13 09:02 UTC, qburst-praven requested changes

2023-09-13 09:02 UTC, qburst-praven commented on scripts/domain-expiry-check/domain_expiry_checker.sh
> +
while I understand the logic, I think both this and the home_directory is useless, and should be removed. You can just add the correct location in domain_list variable.

2023-10-03 03:44 UTC, vyshnavlalqburst commented
Updated the script as per the comments. Removed `username` and `home_directory` variables and updated `domain_list` variable to get the correct location.

2023-10-03 03:53 UTC, qburst-praven approved these changes

2023-10-03 06:06 UTC, merged